version: 2.1

orbs:
  node: circleci/node@4.7
  docker: circleci/docker@2.5.0

# jobs:
#   check-code:
#     docker:
#       - image: circleci/node:14
#     steps:
#       - checkout
#       - run:
#           name: Install Dependencies
#           command: npm install
#       - run:
#           name: Run Tests
#           command: npm test

#   build-and-push:
#     environment:
#       DOCKER_IMAGE: 997909799/ci-cd-k8s
#       DOCKER_TAG: latest
#     executor: docker/docker
#     steps:
#       - setup_remote_docker
#       - checkout
#       - docker/check:
#           docker-username: DOCKER_USER
#           docker-password: DOCKER_PASSWORD
#       - docker/build:
#           image: $DOCKER_IMAGE
#           tag: $DOCKER_TAG
#       - docker/push:
#           digest-path: /tmp/digest.txt
#           image: $DOCKER_IMAGE
#           tag: $DOCKER_TAG
#       - run:
#           command: |
#             echo "Digest is: $(</tmp/digest.txt)"

workflows:
  test-build-deploy:
    jobs:
      - check-code:
          filters:
            branches:
              only: 
                - main
      # - build-and-push:
      #     requires:
      #       - check-code
      #     filters:
      #       branches:
      #         only: 
      #           - main
