apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-app
  namespace: default
  labels:
    app: ci-cd-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ci-cd-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ci-cd-app
    spec:
      containers:
      - name: ci-cd-app-container
        image: 997909799/ci-cd-k8s:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 30101
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app-svc
  namespace: ingress-nginx
spec:
  selector:
    app: ci-cd-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
