apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-cd-app-argocd 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: application-manifet
    repoURL: https://github.com/JustinNguyen9979/app-react-ci-cd.git
    targetRevision: HEAD
  syncPolicy: {}