apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-react
  namespace: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: web-react
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: web-react
    spec:
      containers:
      - name: ci-cd-app-container
        image: 997909799/ci-cd-k8s:1.5.4
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-react-ingress
  namespace: web-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: 172.16.0.16.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web-react
            port: 
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-react
  namespace: web-app
  labels:
    run: web-react
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: web-react

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-app-pvc
  namespace: web-app
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany